### ISSUE TITLE
Setup CI for `master` branch to make exe installers

### ISSUE THREAD

**Issue by robin-swift** [Embroidermodder/Embroidermodder#314]

**Comment by Metallicow** [comment]
As I have said in the past I am a "human being". This may not be an EASY subject.
The way Jon had it was basically just a few as a starter. He had a repo named example 'kubuntu' or 'windows444' without to much confusion. These users then cloned the organisations whole repo structure and then might had added for example "redblackhatVersionEMB" directory to their structure, which is where the built executable would land in(as "BUILT.exe")
This might sound simple and maybe weird to newcomers, but it you value your security, then YES you will build your own executable on your own system.

The way Jon had it before he passed was a few experimental empty repositories for starters. Rule number # 1 for Jon was WE do NOT like .exes or EXECUTABLES. He was a lot like wrye and I respect that point. You can go download 7zip compression library... sorrrrrry that won't work here. THINK AGAIN. If it expands then it is an Expansion library it is potentially dangerous ....(sorry some are confused)

I guess if I had to sum it up myself, then it would be something link this. The Embroidermodder Organization as a whole (2 members) would be able to create an empty repo for "said" OS (operating system), yeah I know this would look lousy but 'flat is better than nested', and then build it independently from here. In any sane persons mind, NO executable will ever be preserved on GitHub(only the verified builders OS).
If one was to try and recreate that idea then the only way I see it now is create a repo called "CI_Built" and remember that's where the built version should land. (Remember that this is extremely dangerous to host to the people)

it is the same as writing a simple script that generates all operating systems in a directory.
Lets just create a repo named "CI_some_orginisation"
Ex:
```
Kubuntu 1.0
Kubuntu 2.0
Kubuntu 2.01
or
Windows ME
Windows XP
Windows 7
...etc...
```

or

nested

```
K--
    Kubuntu 1.0
    Kubuntu 2.0
    Kubuntu 2.01

or

W--
    Windows ME
    Windows XP
    Windows 7

...etc...
```

As you can see indentation DOES matter, tho why does is because the matter at trigger is up to you, therefore it should MATTER to YOU's

All repositories are empty you see.......

**Comment by robin-swift** [comment]
>  Rule number # 1 for Jon was WE do NOT like .exes or EXECUTABLES.

>  In any sane persons mind, NO executable will ever be preserved on GitHub(only the verified builders OS).

Are you saying we shouldn't do Windows installers at all?

Almost all established software that supports Windows has either an `.msi` or `.exe` installer. It's not a short term goal but given that Firefox, GIMP and Inkscape distribute them then it's clearly viable for cross-platform FOSS applications.

**Comment by Metallicow** [comment]
Im not sure how many websites there was ... But GitHub hosted the source
for building and the website code. There was something weird going on how
he setup embroidermoddder.org with the DNS folks which by the way where all
clueless as how to do anything or know where it was going. And there was at
least a third site that was completely compiled and it also had something
happen shortly after he passed. Very suspicious as to why someone would
want into it... Having a server with all the built exes on it makes sense,
but it also presents the "all eggs in one basket" scenario. Servers also
cost upkeep but makes no sense to me why it took years later for the others
to finally say the second website went down. It appears the service
providers are taking money and then attacking the sites. But obviously
whoever hosts the builds should be wary of a breakin hacker which could
result in modified downloads. As far as I know the embroidermoddder.org
site he setup had the major 4-5 original 2.0alpha builds. Other builds was
probably happening on the other site due to security concerns... But here
on GitHub is just the source code. I hope you can make sense of all this...

**Comment by robin-swift** [comment]
> the "all eggs in one basket" scenario

I've been cloning the github repositories to gitlab every so often as an insurance.

https://gitlab.com/embroidermodder

> I know the embroidermoddder.org site he setup had the major 4-5 original 2.0alpha builds

What I can do is house a copy of the most recent builds (archives, .deb, .mdi etc.) in the www.libembroidery.org repository in the `public/` folder. These would get replaced to stop the storage getting too high, but there would be at least one for each minor version number after 2.0.

These would also then be copied over to gitlab along with everything else during my backup work.

**Comment by Metallicow** [comment]
If I really wanted to do the work, you wouldnt have to pay for anything. If
Jon was here, the cost would be zero. If I had my friends cover the cost it
would still be negligible. Why we should be the targets of the earth is be
onde our knowledge, and even if it cort bad, then who would you have to
blame? Why me and how?

**Comment by robin-swift** [comment]
I'm not sure what you mean. I'm not asking you to do anything.

I'm going to place an issue in the www.libembroidery.org repository about this storage issue and if you have more to say I'd prefer you'd follow up [there](https://github.com/Embroidermodder/www.libembroidery.org/issues/1).

The original task described by this issue is about getting the WIX installer generator to work inside github actions but that doesn't seem necessary since the main purpose of the automated build is to see if the program has bugs on other OSs. So I'm closing this.

**Comment by Metallicow** [comment]
@RobinSwift One of the points that Jon made clear was "We are not creating
a format." Yet it is clear that it is necessary to modify the format at
times.
I hope you intererate it correctly.

**Comment by Metallicow** [comment]
This is a problem with society Recent Examples on the WebWasm components
are interchangeable, so a component written in one language (such as
Python) can *interoperate *with a component written in other language
entirely (say, Rust).—Justin Warren, *Forbes*, 18 Apr. 2023The legislation
limits personal-data sharing, forces operating system owners to allow the
download of apps outside of their respective app stores, and orders
messaging services to *interoperate *with smaller platforms, among other
provisions. Averting a data crisis.—Jacob Carpenter, *Fortune*, 25 Mar. 2022The
European Commission says Broadcom’s plan to acquire cloud computing company
VMware has the potential to limit competition for a couple of hardware
components that *interoperate *with VM’s software.—David Meyer, *Fortune*,
13 Apr. 2023
Short for border gateway protocol, BGP is a technical specification that
organizations that route traffic, known as autonomous system networks, use
to *interoperate *with other ASNs.—Dan Goodin, *Ars Technica*, 23 Sep. 2022The
delays and dangers will increase until smart devices *interoperate *on a
data network.—Brian Platz, *Forbes*, 30 June 2022IoT brings a whirlwind of
changes to the traditional working landscape by creating a network of
*interoperating *devices that can automate tasks, perform decision-making
autonomously and assist in a host of tasks at the user’s command.—Jyoti
Prasad Bhatt, *Forbes*, 22 Feb. 2023Meanwhile, companies including IT
consulting company Infosys, data security firm Okera, and A.I. automation
company DataRobot have all agreed to make their outside software apps
*interoperate *with Snowflake's systems.—Aaron Pressman, *Fortune*, 8 June
2021Now, everything can be stored securely except for email, calendar and
contacts functions that need to *interoperate *with multiple providers.—Joseph
Menn, *Washington Post*, 7 Dec. 2022

**Comment by robin-swift** [comment]
I'm struggling to read and interpret what you just sent [here](https://github.com/Embroidermodder/Embroidermodder/issues/314#issuecomment-1550805058).

Since you're using email rather than the GitHub website I'm not sure what limitations that puts on formatting your messages. For example the using asterisks for emphasis renders on GitHub as italic *like this* but your message isn't rendering that. If you're sending more than one sentence could you please use the website?

> [@robinswift](https://github.com/robinswift) One of the points that Jon made clear was "We are not creating
a format." Yet it is clear that it is necessary to modify the format at
times.
> I hope you intererate it correctly.

If you can offer a simple example of when that is necessary we can start a new GitHub issue about that. I won't be altering the behaviour of formats outside of what I can interpret in their behaviour so there's currently little risk of me interating that incorrectly.

Or perhaps it would be more useful for you to tell me what you wanted this software to do more generally? I have notes in the todo list and old issues but a lot of that is 8 or so years old at least.

**Comment by Metallicow** [comment]
Whether I reply from "email" or directly, the message should remain the
same. Readability counts. I am replying from a "smart" phone, which isn't
too smart. The glyph that it is based upon contains no points, therefore
the "blank" matrix might be similar to kids today trying to scribble a
letter on a "smartwatch" and have some sort of result(I interpreted a
glyph) curve that resulted in "s" or so....

**Comment by Metallicow** [comment]
The worst part is folks that didn't support the project. I have a list of
all of them, as we have a list of those that did. Those that actually
supported the project has a font ready to run any machine within means.
Legally only those who helped the project has rights to destruction. But we
also realize others don't comply. Some don't understand.
