### ISSUE TITLE
Where can I find OSX binary?  Or how to build on OSX?

### ISSUE THREAD

**Issue by hariedo** [Embroidermodder/Embroidermodder#45]
I was able to qmake the project on my Linux box, but I wasn't able to find any build instructions or prebuilt OSX binaries.  Can you put up a wiki page to show how the build process works there?

**Comment by forresto** [comment]
What's the state of this now??

**Comment by redteam316** [comment]
The travis-osx64 repository shows every step for this aside from installing homebrew. I've been a bit hesitant to copy the basic info into the readme yet because there are still some issues with the bundle and some minor changes that will occur in the app itself.

I've been in conversation with another Mac user about some of the issues this week.

**Comment by hariedo** [comment]
If someone is thinking of doing the build for OSX, and can produce usable Brother SE 400 files, I'd be happy to pitch in a couple hundred bucks to get this over the finish line.

**Comment by forresto** [comment]
Nightly OSX 64 just crashes for me on opening. I'm on El Capitan 10.11.2.

**Comment by JoshVarga** [comment]
I will test that build on my Macbook Pro and see what happens I should be
able to get a clean build

On Sun, Jan 17, 2016 at 10:14 AM, Forrest Oliphant <notifications@github.com
