### ISSUE TITLE
Menu buttons missing on OSX build, QT creator, latest OSX SDK 10.9

### ISSUE THREAD

**Issue by Penrock1547** [Embroidermodder/Embroidermodder#59]
Hello - trying to build on OSX 10.9.5 using QT Creator

On first try, get a build error:

![untitled1](https://cloud.githubusercontent.com/assets/2353066/4569781/d34676da-4f50-11e4-8ecd-d3727f5a1b1f.jpg)

QT website says this may be due to having latest OSX SDK installed (Xcode 6...10.9) so they advise to change this file as follows: 

![untitled](https://cloud.githubusercontent.com/assets/2353066/4569797/1c17fb72-4f51-11e4-98f0-be5af0fbfdf8.jpg)

Alternative solution from QT was to re-install old version of SDK (10.8)
After that, build succeeds..then try to run and get the following in application output

Starting /Users/jxxxxx/Embroidermodder-master/build-embroidermodder2-Desktop_Qt_5_3_clang_64bit-Debug/embroidermodder2.app/Contents/MacOS/embroidermodder2...
Reading Settings...
LayoutState NOT restored! Setting Default Layout...
language: default
CmdPrompt Constructor
CmdPromptInput Constructor
CmdPromptHistory Constructor
CmdPromptSplitter Constructor
CmdPromptHandle Constructor
CmdPromptHandle Constructor
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
QLayout: Attempting to add QLayout "" to PropertyEditor "", which already has a layout
Creating All Actions...
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'layerselector')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'colorselector')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'linetypeselector')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'lineweightselector')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'hidealllayers')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'showalllayers')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'freezealllayers')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'thawalllayers')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'lockalllayers')
QObject::connect: No such slot MainWindow::stub_implement() in ../embroidermodder2/mainwindow-actions.cpp:186
QObject::connect:  (sender name:   'unlockalllayers')
MainWindow createAllMenus()
MainWindow createFileMenu()
MainWindow createEditMenu()
MainWindow createViewMenu()
MainWindow createSettingsMenu()
MainWindow createWindowMenu()
MainWindow createHelpMenu()
MainWindow createAllToolbars()
MainWindow createFileToolbar()
MainWindow createEditToolbar()
MainWindow createViewToolbar()
MainWindow createZoomToolbar()
MainWindow createPanToolbar()
MainWindow createIconToolbar()
MainWindow createHelpToolbar()
MainWindow createLayerToolbar()
MainWindow createPropertiesToolbar()
MainWindow createTextToolbar()
MainWindow createPromptToolbar()
MainWindow::updateMenuToolbarStatusbar()
MainWindow::hideUnimplemented()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
tipOfTheDay()
ImageWidget Constructor
buttonTipOfTheDayClicked(8)
ImageWidget Destructor
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()
MainWindow::resizeEvent()

This is the result (many buttons missing):

![untitled3](https://cloud.githubusercontent.com/assets/2353066/4569817/70a30722-4f51-11e4-8817-1363540f12cc.jpg)

**Comment by joerghermann** [comment]
Happy new 2015!
I installed Qt 5.4 and was able to compile em2 on Mac OS X 10.9.5 without the SDK hickup.
Still the icons are missing. The em2.app bundle is created in the same directory as em2.pro.
I also tried to copy the icons directly into the em2.app bundle, no change.
Has anyone a hint how this can be solved?

**Comment by redteam316** [comment]
Where did you copy the icons directory into the bundle? Was it
embroidermodder2.app/Contents/MacOS/icons

**Comment by joerghermann** [comment]
Yes, I copied the icons folder into embroidermodder2.app/Contents/MacOS
Next try I copied the executable from the bundle into the folder embroidermodder2. This way the folder icons is on the same level as the executable - again no icons visible.

**Comment by redteam316** [comment]
I tried upgrading to mavericks tonight but it's not possible for me since I didn't grab it when it was available apparently. See this for more information: http://apple.stackexchange.com/questions/151906/how-do-i-install-mavericks-now-that-yosemite-has-been-released
As such, I can't personally verify the problem myself on Mavericks(you can thank Apple for that). What I can do is help you towards a solution. This is a fairly common question that is usually simple to solve but as you can see from the previous situation that @essence-of-orange encountered, sometimes it's caused by other applications or things that aren't exactly in our control. Knowing the cause will help us prevent this in the future.

It sounds like you are doing everything properly and seem to know what you are doing so try these:

1) Did you check for any file permission problems as previously discussed?

2) You can try adding
```CONFIG -= app_bundle```
into the embroidermodder2.pro file to build it that way. I'm not aware of exactly what differences there are in this process since you say it runs but is just not displaying the icons, I would guess that it simply skips the bundling process and that the binary is exactly the same.

3) Make sure you are running the embroidermodder2 binary from the same folder it is located in. Regardless of whether the binary is in a bundle or not, I would expect this to work the same. I.E.
```
cd /path/to/embroidermodder2
./embroidermodder2
```

4) Is there any problem with you upgrading to Yosemite? This may hose my OSX installation, and if it does, it will slow things down as far as OSX until I can get it reinstalled/BIOS upgrade and sorted out. If it goes without a hitch, things could be great :P

**Comment by joerghermann** [comment]
1) Files all owned by me and 755 permission - looks fine.
2) Indeed only the executable is built, no app bundle.
3) Partial success: Double clicking the executable within the directory starts it, again without icons.
Starting from a terminal with a cd beforehand as you suggested indeed displays em2 in all it's glory! Hooray!
4) Yes and no: I have 10.6.8 and 10.9.5 available. I will ask a friend for 10.10 help.

What is your Mac OS?
Please do not harm your installation!

**Comment by redteam316** [comment]
3) Excellent, for OSX then it seems that the main obstacle is to make the bundle execute a shell script which changes to the proper directory before launching the binary itself. This is normal behavior with unix(which OSX is based on) but depending on the desktop/file manager may expose the problem or not depending on the situation. How would most OSX users(including you had you not compiled from source) start the application? I would think most would start it from the dock or double clicking a bundle or .dmg....I think I'm really just asking for all situations here just to cover bases. I'm much more fluent with other os(Linux, Windows) than OSX. 

4) I have 10.6.8 (Snow Leopard) and 10.8.5 (Mountain Lion). I'm not too worried about harming my installation, I have plenty of fallbacks and have blown all of them up more times than you have fingers. I'll be testing 10.10 probably soon now that I realize there are cutoffs for OSX, just preferably not on the fly :D

If you would like to provide a patch for making this easier for OSX users, they would be most appreciative. Otherwise, any other info you can provide is helpful.

**Comment by joerghermann** [comment]
I think we can rule out dependencies on OS versions by now and will proceed on 10.9.
As you say _all_ Mac users start applications by clicking on the app/bundle.

My friend suggested using resources: Straightforward, platform independent, and stable for years by now. I read your comment on resources above. I am convinced the cross platform benefits by far  outweigh the commodity of replacing png files. After reading this abstract I feel confident, that resources are the way to go:
http://qt-project.org/doc/qt-4.8/resources.html
Still I am in no position to take a decision on this topic.

**Comment by redteam316** [comment]
Thank you, i wasn't sure if I was comparing Apples to Oranges when it came to os differences, The differences are seemingly small though. I just need to understand them.

Using resources on the other hand is not straightforward. It does not take into account that all operating systems will adhere to it. Qt has a resource system only because of the underlying operating systems. If those change drastically or are obsolete in the future, will not save any developer time as we will have to change to suit the system. C++ now has a filesystem; I can only imagine that eventually it will adopt Signals/Slots too. Would I be wrong to drop Qt then? Likely not, but I use it because it solves many other problems I have to relate with.

Using Qt resources IS a good idea, it just doesn't align with our goal. Embedding resources doesn't mean just icons. I am dead. It doesn't matter how or why.We all die. The user now can download our application and use it as normal. When the user decides that they need to extend our program, all they need is a basic knowledge of javascript. They do not need to recompile the program at all. If we were to embed the basic commands into the application as resources, and that person isn't fluent with all three C++/Qt/Javascript, they would stop right there.

When I joined this project, most of the publicly available code was in MSVC C++, C#, or worse since it didn't run on any os other than Windows. Since then, we have ported the formats to C(the most portable language), which now are easily exported to many different languages. The GUI was ported to Qt simply because it was the best solution available. While Qt shares a common goal of portability and usability with our project, it cannot be relied upon as an eternal crutch. Many early versions of libembroidery used Qt, now it is it's own library. Embroidermodder 2 is merely the GUI of the former version with additional features.

I am a certified Qt Specialist so it may be hard to convince me to switch away from Qt, but it's much harder to convince me that hard-coding essential data is beneficial to the longevity of any project.

That being said, I'm open to any suggestions of technical merit or improve the quality or longevity of the existing code and will keep an open mind.

**Comment by redteam316** [comment]
@joerghermann,
I just pushed a couple of commits that should fix the issue you are having.
Travis-CI build passes using Qt 5.4.0 on OSX 10.9.5 as seen here: https://travis-ci.org/Embroidermodder/travis-osx64/builds/46950426
The resulting test build can be downloaded here: https://github.com/Embroidermodder/nightly-ci/archive/osx64.zip

I would also like you to verify this by recompiling using the latest version on your machine. It should work, but I've only tested on Linux at this point.
