### ISSUE TITLE
Converting from PES to VP3, only the first few stitches carried across

### ISSUE THREAD

**Issue by essence-of-orange** [Embroidermodder/Embroidermodder#60]
See attached files...

Original: http://upfile.mobi/675600
Saved: http://upfile.mobi/675603

If this could be fixed I'd be very greatful :)

**Comment by Drahflow** [comment]
The PR solves the original issue, i.e. missing stitches. They happened because the logic for counting number of colors did not issue a new color when encountering a STOP/END-Stitch but the main stitch-data logic did.

It is debatable what is the correct thing to do here. I know of no way to make the machine cut the thread withouth issuing a new color. The proposed solution will create a new color (which is in fact identical to the old color) when encountering a STOP.
