### ISSUE TITLE
[Q] have you considered forking LibreCAD?

### ISSUE THREAD

**Issue by SSoulaimane** [Embroidermodder/Embroidermodder#68]

**Comment by redteam316** [comment]
Yes, it was considered several years ago and we decided against it for various reasons(some being technical reasons, others non-technical). If the LibreCAD developers wish to incorporate libEmbroidery (which handles reading and writing the embroidery formats) into LibreCAD, then that is entirely possible. The main reason that the format handling code was broken out was so that other projects could use it too.
